#include "testing.h"

void cyclePumps() {
  pumpToState(PUMP0, PUMPON);
  delayRough();
  pumpToState(PUMP1, PUMPON);
  delayRough();
  pumpToState(PUMP2, PUMPON);
  delayRough();
  pumpToState(PUMP3, PUMPON);
  delayRough();
  pumpToState(PUMP4, PUMPON);
  delayRough();
  pumpToState(PUMP0, PUMPOFF);
  delayRough();
  pumpToState(PUMP1, PUMPOFF);
  delayRough();
  pumpToState(PUMP2, PUMPOFF);
  delayRough();
  pumpToState(PUMP3, PUMPOFF);
  delayRough();
  pumpToState(PUMP4, PUMPOFF);
  delayRough();
}

void cycleValves() {
  valveToState(VALVE0, VOPEN);
  delayRough();
  valveToState(VALVE0, VCLOSED);
  delayRough();
  valveToState(VALVE1, VOPEN);
  delayRough();
  valveToState(VALVE1, VCLOSED);
  delayRough();
  valveToState(VALVE2, VOPEN);
  delayRough();
  valveToState(VALVE2, VCLOSED);
  delayRough();
  valveToState(VALVE3, VOPEN);
  delayRough();
  valveToState(VALVE3, VCLOSED);
  delayRough();
  valveToState(VALVE4, VOPEN);
  delayRough();
  valveToState(VALVE4, VCLOSED);
  delayRough();
  valveToState(VALVE5, VOPEN);
  delayRough();
  valveToState(VALVE5, VCLOSED);
  delayRough();
  valveToState(VALVE6, VOPEN);
  delayRough();
  valveToState(VALVE6, VCLOSED);
  delayRough();
  valveToState(VALVE7, VOPEN);
  delayRough();
  valveToState(VALVE7, VCLOSED);
  delayRough();
  valveToState(VALVE8, VOPEN);
  delayRough();
  valveToState(VALVE8, VCLOSED);
  delayRough();
  valveToState(VALVE9, VOPEN);
  delayRough();
  valveToState(VALVE9, VCLOSED);
  delayRough();
  valveToState(VALVE10, VOPEN);
  delayRough();
  valveToState(VALVE10, VCLOSED);
  delayRough();
  valveToState(VALVE11, VOPEN);
  delayRough();
  valveToState(VALVE11, VCLOSED);
  delayRough();
  valveToState(VALVE12, VOPEN);
  delayRough();
  valveToState(VALVE12, VCLOSED);
  delayRough();
  valveToState(VALVE13, VOPEN);
  delayRough();
  valveToState(VALVE13, VCLOSED);
  delayRough();
  valveToState(VALVE14, VOPEN);
  delayRough();
  valveToState(VALVE14, VCLOSED);
  delayRough();
  valveToState(VALVE15, VOPEN);
  delayRough();
  valveToState(VALVE15, VCLOSED);
  delayRough();
  valveToState(VALVE16, VOPEN);
  delayRough();
  valveToState(VALVE16, VCLOSED);
  delayRough();
  valveToState(VALVE17, VOPEN);
  delayRough();
  valveToState(VALVE17, VCLOSED);
  delayRough();
  valveToState(VALVE18, VOPEN);
  delayRough();
  valveToState(VALVE18, VCLOSED);
  delayRough();
  valveToState(VALVE19, VOPEN);
  delayRough();
  valveToState(VALVE19, VCLOSED);
  delayRough();
}